### PR TITLE
Adjust product description proposal

### PR DESCRIPTION
**Pull request by yostashiro**

### CODE REVIEW

**Comment by yostashiro** [comment]
@TimLai125 Please review.

**Comment by TimLai125** [comment]
Should we change the module name (sale_logic_adj_pci) or consider combining two modules?

**Comment by yostashiro** [comment]
> Should we change the module name (sale_logic_adj_pci) or consider combining two modules?

@TimLai125 Could be good to combine the modules into one (`product_description_adj` to survive) for better maintenance.  Can you take care of this.

**Comment by TimLai125** [comment]
ok, I will commit later

**Comment by yostashiro** [comment]
> ok, I will commit later

@TimLai125 You can proceed with all the rest of the steps (incl. communicating w/ the customer)

**Comment by TimLai125** [comment]
This PR is taken over by #48

**Pull request closed without merging**
