### PR TITLE
[10.0][T991][FIX]: Fix Error while testing on copy DB/PCI testdb

### PR DESCRIPTION
**Pull request by YogeshMahera-SerpentCS**
TASK [T991](https://www.quartile.co/web#id=991&action=771&model=project.task&view_type=form&menu_id=505)
Steps to Reproduce the issue.

1 go to https://copy-pci-dealers.quartile.co/ 
2 Add some item in the cart and add some comment in the comment box
3 pay with PayPal 
4 check the console and you'' find the Odoo Server Error as below.

Fixed Error:
{
   "message":"Odoo Server Error",
   "code":200,
   "data":{
      "debug":"Traceback (most recent call last):\n  File \"/odoo/odoo/odoo/http.py\", line 642, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/odoo/odoo/odoo/http.py\", line 684, in dispatch\n    result = self._call_function(**self.params)\n  File \"/odoo/odoo/odoo/http.py\", line 334, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/odoo/odoo/odoo/service/model.py\", line 101, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/odoo/odoo/odoo/http.py\", line 327, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/odoo/odoo/odoo/http.py\", line 942, in __call__\n    return self.method(*args, **kw)\n  File \"/odoo/odoo/odoo/http.py\", line 507, in response_wrap\n    response = f(*args, **kw)\n  File \"/odoo/custom/pci-private/website_product_stock/controllers/main.py\", line 62, in payment_transaction\n    kwargs=kwargs)\n  File \"/odoo/odoo/odoo/http.py\", line 507, in response_wrap\n    response = f(*args, **kw)\n  File \"/odoo/odoo/addons/website_sale/controllers/main.py\", line 822, in payment_transaction\n    tx = request.website.sale_get_transaction()\n  File \"/odoo/odoo/addons/website_sale/models/sale_order.py\", line 491, in sale_get_transaction\n    if transaction.state != 'cancel' and transaction.acquirer_id.provider != 'sips':\n  File \"/odoo/odoo/odoo/fields.py\", line 930, in __get__\n    value = record._cache[self]\n  File \"/odoo/odoo/odoo/models.py\", line 5603, in __getitem__\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/odoo/odoo/odoo/fields.py\", line 48, in get\n    raise self.exception\nMissingError: (u'Record does not exist or has been deleted.', None)\n",
      "exception_type":"missing_error",
      "message":"Record does not exist or has been deleted.\nNone",
      "name":"odoo.exceptions.MissingError",
      "arguments":[
         "Record does not exist or has been deleted.",
         null
      ]
   }
}

### CODE REVIEW

**Comment by yostashiro** [comment]
@YogeshMahera-SerpentCS Please rebase to declutter the commit history.

Please also address here https://github.com/qrtl/pci-custom/pull/178#issue-427911276 how you would reproduce the issue.

**Comment by YogeshMahera-SerpentCS** [comment]
Hi @TimLai125 
Added module pr1_multi_website-shop as a dependency: 
This module overrides the base views `website_sale.product_public_category_form_view` and replace their own view
So in that case, I have made them a dependency and inherit the `pr1_multi_website-shop.v_pr1_multi_pwebsite_cats`  view.

**Comment by TimLai125** [comment]
@YogeshMahera-SerpentCS As discussed last week, please state why we need this to fix the issue. Otherwise, we do not know whether this change is a valid fix or not if we are not clear about the cause.
https://github.com/qrtl/pci-custom/pull/178/files#diff-1512911567143d28d9c4b2471793180aL13-R13

**Comment by YogeshMahera-SerpentCS** [comment]
Hi, @TimLai125 Yes I have noted the log and traceback. here is the following result.
-  Added Print statement here
- https://github.com/odoo/odoo/blob/10.0/odoo/models.py#L4473

1: With using Sudo() getting the following data were the errors:
  - ('self.env.user', res.users(1,))
('Self', sale.order(9785,))
('existing', sale.order(9785,))
('self.env.user', res.users(1,))
('Self', payment.transaction(2044,))
('existing', payment.transaction())
`Record does not exist or has been deleted`
('self - existing', payment.transaction(2044,))
('self - existing', payment.transaction(2044,))
('self - existing', payment.transaction(2044,))

2:  Without using Sudo() getting the following values.
  - ('self.env.user', res.users(1,))
('Self', sale.order(9785,))
('existing', sale.order(9785,))
('self.env.user', res.users(1,))
('Self', payment.transaction(2044,))
('existing', payment.transaction(2044,))


3: Following fields which have Record does not exist:

('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.partner_phone)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.acquirer_id)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.fees)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.type)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.acquirer_reference)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.create_uid)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.partner_zip)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.currency_id)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.partner_lang)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.partner_address)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.write_uid)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.write_date)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.paypal_txn_type)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.partner_country_id)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.partner_city)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.amount)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.reference)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.state)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.partner_id)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.partner_email)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.html_3ds)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.create_date)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.state_message)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.payment_token_id)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.partner_name)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.date_validate)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.callback_eval)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.sale_order_id)
('value', <odoo.fields.FailedValue object at 0x7f489c419d10>, <class 'odoo.fields.SpecialValue'>, payment.transaction.state)

More updates about this PR:

Added Print Statment

Till now everything works but code stop working at this line:

https://github.com/odoo/odoo/blob/10.0/addons/website_sale/controllers/main.py#L831

More looked on this method `sale_get_transaction`

https://github.com/odoo/odoo/blob/91807404e7d5c314ea30926b44bd16e878417ec1/addons/website_sale/models/sale_order.py#L490

Added Print Statement above the line:

Till now also getting id with browse record. but when I try to access any field like state, acquirer_id of payment transaction it will throw the error Record does not exist. It seems unable to access any fields of a payment transaction.

**Comment by TimLai125** [comment]
@YogeshMahera-SerpentCS The relation between removing the sudo() (https://github.com/qrtl/pci-custom/pull/178/files#diff-1512911567143d28d9c4b2471793180aL13) 
and method here is not clear. https://github.com/odoo/odoo/blob/91807404e7d5c314ea30926b44bd16e878417ec1/addons/website_sale/models/sale_order.py#L490
Please check why passing sudo() to `sale_get_order` will affect the `sale_get_transaction`, and also in case there is some actions on the JS side which affects the logic as well.

**Comment by TimLai125** [comment]
@YogeshMahera-SerpentCS FYI, cannot reproduce the issue in copy environment anymore.

**Comment by YogeshMahera-SerpentCS** [comment]
Hi, @TimLai125 before merging this task to production we need to merge this PR to staging branch, 
Here are the following reasons to merge this PR.

1: In current PR we updated code for XML view changes(which is required to update a field on XML view) and fixed dependency issues.
2: In Odoo Base and Any customized module we didn't find anywhere where the Sudo added after the `request.website.sudo().sale_get_order()` so fo surety and safe side can we keep this PR?

**Pull request closed without merging**
